trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: ./variables/variables.yml

# replace with a template.
stages:
- stage: DeployToAzure
  jobs:
  #- template: jobs/transpile-infra.yml
  - template: jobs/validate-or-deploy-infra.yml
    parameters:
      deploymentMode: 'Validation'
      jobName: ValidateInfra
      jobDisplayName: 'Validate Infra'
      dependsOn: ''
  - template: jobs/validate-or-deploy-infra.yml
    parameters:
      deploymentMode: 'Incremental'
      jobName: DeployInfra
      jobDisplayName: 'Deploy Infra'
      dependsOn: 'ValidateInfra'