trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: variables/variables.yml

# replace with a template.
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "Hello, world!"
      displayName: 'Run a one-line script'