trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: ./variables/variables.yml

stages:
- stage: DeployToAzure
  jobs:
  - template: jobs/validate-or-deploy-infra.yml
    parameters:
      deploymentMode: 'Validation'
      jobName: ValidateInfra
      jobDisplayName: 'Validate Infra'
      dependsOn: ''
      keyVaultName: ${{ variables.keyVaultName }}
  - template: jobs/validate-or-deploy-infra.yml
    parameters:
      deploymentMode: 'Incremental'
      jobName: DeployInfra
      jobDisplayName: 'Deploy Infra'
      dependsOn: 'ValidateInfra'
      keyVaultName: ${{ variables.keyVaultName }}